#!/usr/bin/env bash
# sync.sh - distribute the canonical governance files to member repos.
#
# Copies:
#   governance/constitution.md -> <member>/policies/constitution.md
#   governance/root-CLAUDE.md  -> <workspace-root>/CLAUDE.md
#
# Copies are managed: they carry a header pointing back to this repo.
# A copy that was edited locally is left alone (a notice is printed);
# pass --force to overwrite it.
set -euo pipefail

GOV_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$GOV_DIR/.." && pwd)"
FORCE=0
[ "${1:-}" = "--force" ] && FORCE=1

MEMBERS=(
  backend/rest-api
  backend/etl
  backend/scudo
  backend/doris-cluster
  backend/postgres-omop
  frontend/isciii-ciber
  helm-chart
  devops-infra/quality
  devops-infra/tcms
  devops-infra/artifacts-repos
)

HEADER="<!-- Managed copy of governance/constitution.md. Edit the canonical file in the governance repo and re-run governance/sync.sh. Do not edit this file. -->"

sync_one() {
  local src="$1" dest="$2"
  if [ -f "$dest" ] && [ "$FORCE" -ne 1 ] && ! diff -q "$src" "$dest" >/dev/null 2>&1; then
    echo "SKIP (locally modified; use --force to overwrite): $dest"
    return
  fi
  if [ -f "$dest" ] && [ "$FORCE" -eq 0 ] && diff -q "$src" "$dest" >/dev/null 2>&1; then
    echo "OK   (up to date): $dest"
    return
  fi
  mkdir -p "$(dirname "$dest")"
  cp "$src" "$dest"
  echo "SYNCED: $dest"
}

for m in "${MEMBERS[@]}"; do
  if [ ! -d "$ROOT/$m" ]; then
    echo "WARN (member directory missing; remove from MEMBERS if gone): $ROOT/$m"
    continue
  fi
  dest="$ROOT/$m/policies/constitution.md"
  if [ -f "$dest" ] && [ "$FORCE" -ne 1 ] && ! diff -q <(printf '%s\n' "$HEADER"; cat "$GOV_DIR/constitution.md") "$dest" >/dev/null 2>&1; then
    echo "SKIP (locally modified; use --force to overwrite): $dest"
    continue
  fi
  mkdir -p "$(dirname "$dest")"
  { printf '%s\n' "$HEADER"; cat "$GOV_DIR/constitution.md"; } > "$dest"
  echo "SYNCED: $dest"
done

sync_one "$GOV_DIR/root-CLAUDE.md" "$ROOT/CLAUDE.md"
echo "Done. Commit the synced files in each member repo."
